### ISSUE TITLE
F-Droid inclusion 

### ISSUE THREAD

**Issue by shuvashish76** [hzy3774/AndroidP7zip#26]
@hzy3774 I understand this project is for your learning purpose, but why not let others enjoy it. & what is better than F-Droid for reaching bigger FOSS community...

Request for packaging has been opened here: https://gitlab.com/fdroid/rfp/-/issues/1888

Thanks to @IzzySoft the app is now available on Izzy repo.
https://apt.izzysoft.de/fdroid/index/apk/com.hzy.p7zip.app

🤗

**Comment by IzzySoft** [comment]
Someone called my name… Yes, I was asked to and gladly complied. If you wish to link there (e.g. from your Readme), you can find [some badges here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :wink:

**Comment by hzy3774** [comment]
Really appreciate with your advice, and thank you for your packaging request!👍

**Comment by shuvashish76** [comment]
@hzy3774 Can you please make following changes as mentioned here?
https://gitlab.com/fdroid/rfp/-/issues/1888#note_713413770

**Comment by IzzySoft** [comment]
Done easily:

1. merge that PR
2. tag a new release :smile:

(in case you wonder: my repo uses the very same software as F-Droid itself, so I had this already prepared for use with that)

**Comment by IzzySoft** [comment]
Thanks! First step is done. Now we only need a tag for (probably) v1.7.2

**Comment by shuvashish76** [comment]
I guess v1.7.2 coming in 2023 only (from previous [releases](https://github.com/hzy3774/AndroidP7zip/releases) pattern 🙈)

**Comment by hzy3774** [comment]
> Thanks! First step is done. Now we only need a tag for (probably) v1.7.2

tag and release done, thank you!

**Comment by IzzySoft** [comment]
Thanks! Transferred that update over to the RFP. A team member hopefully picks it up soon. Should there be questions concerning build or review, we might need to come back to you – but ideally only with the information "it's done" :smile:

**Comment by shuvashish76** [comment]
@hzy3774 
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10003#note_719329533

> _Issuebot and [VT](https://www.virustotal.com/gui/file/ecd56e77e1a62ec50a4d071944c7ab528ca9abbe301a6b88b3f12854cea2cf67/details) look good. Tested on device. It can't find my zip files. It seems it apply a filter and only media files are displayed. The file browser is pretty slow and difficult to use. When I press back the whole app quit instead of returning to parent directory. I thought it's better to use SAF for file browser. The app crashes if I tap on the file list before an operation finishes._

```
FATAL EXCEPTION: main
Process: com.hzy.p7zip.app, PID: 32632
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{a84faf5 position=7 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{a0f674d VFED.V... ........ 0,0-1080,1575 #7f0900b0 app:id/fragment_storage_list}, adapter:com.hzy.p7zip.app.adapter.FileItemAdapter@b9a53c5, layout:androidx.recyclerview.widget.LinearLayoutManager@599e11a, context:com.hzy.p7zip.app.activity.MainActivity@af07fdb
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

> _This app needs to be more polished before publishing._

**Comment by shuvashish76** [comment]
@hzy3774 any updates?

**Comment by asthagarg2428** [comment]
How can I support a password protected zip and 7zip files?
Which command do I need for that? and from where can I get all the commands ?

**Comment by shuvashish76** [comment]
@asthagarg2428 please create a separate issue for that.
The topic of this issue is about "F-Droid inclusion"

**Comment by asthagarg2428** [comment]
> @asthagarg2428 please create a separate issue for that.
> The topic of this issue is about "F-Droid inclusion"

I already have but not getting prompt responses so thought of asking people who already have implemented this library

**Comment by IzzySoft** [comment]
@hzy3774 could you please add the APK to the latest tag so the app is at least up-to-date in my repo? Thanks!
